# -*- coding: utf-8 -*-
"""
One slide spec per narration BEAT, per module.

`None` = this beat keeps real app footage instead of a slide.
The deck renderer (deck.py) and the video frame renderer (frames.py) both read this,
so the .pptx and the video can never disagree.

MODULES[n] = dict(title=, sub=, beats=[...])   len(beats) == number of narration paragraphs
"""

import os

SHOTS = os.path.abspath(os.path.join(os.path.dirname(__file__),
        "..", "..", "..", "CineSeat", "PresentationAssets", "screenshots"))


def shot(name):
    return os.path.join(SHOTS, name)


def asset(name):
    return os.path.abspath(os.path.join(SHOTS, '..', name))


MODULES = {}

SLIDES = {}


# ---------------------------------------------------------------- Module 00
SLIDES[0] = [
    dict(layout="points", kicker="Every app, the same substrate",
         title="Three foundations under every iOS app",
         items=["**A language.** Swift",
                "**A set of tools.** Xcode",
                "**A way of connecting** what's on screen to code that runs"],
         image=shot("01_showings_landing.png")),
    dict(layout="points", kicker="By the end of this video you will know",
         title="Course objectives",
         items=["How the eleven modules are structured, and why in that order",
                "What you need to follow along — and what you don't",
                "How the example app is used, and why it isn't the point",
                "What to do with each module's practice exercise"]),
    dict(layout="compare", kicker="Two halves", title="How the course is built",
         cols=[dict(head="Modules 1–7",
                    items=["The technical curriculum", "It climbs deliberately",
                           "Each one needs the one before it"]),
               dict(head="Chapters 8–10",
                    items=["The craft no single API teaches you",
                           "Case study, testing, documentation"])]),
    dict(layout="table", kicker="The technical curriculum", title="It climbs",
         rows=[("01", "The language and the tools — Swift, Xcode"),
               ("02", "The interface layer — UIKit, MVVM, Auto Layout"),
               ("03", "Intermediate Swift and concurrency"),
               ("04", "Networking — real data"),
               ("05", "Data persistence and security"),
               ("06", "Architecture — keeping it maintainable"),
               ("07", "Device capabilities — maps, notifications, media")]),
    dict(layout="table", kicker="Three craft chapters", title="What no single API teaches",
         rows=[("08", "Case study — assembling it into one product"),
               ("09", "Testing — proving it works"),
               ("10", "Documentation — whether your work survives handover")]),
    dict(layout="compare", kicker="Every module ends with a practice exercise",
         title="Why they matter",
         cols=[dict(head="Watching someone write code", warn=True,
                    items=["feels like learning"]),
               dict(head="Writing it yourself", ok=True,
                    items=["is where it becomes yours"])],
         verdict="Do them."),
    dict(layout="chips", kicker="What you need", title="Three things",
         chips=[("A Mac", "iOS needs macOS"), ("Xcode", "free, Mac App Store"),
                ("Apple account", "free")]),
    dict(layout="compare", kicker="You don't need a physical iPhone",
         title="Simulator or device?",
         cols=[dict(head="The simulator", ok=True,
                    items=["covers almost everything in this course"]),
               dict(head="A real device",
                    items=["eventually — camera and sensors"])],
         verdict="But not to learn."),
    dict(layout="compare", kicker="How the example app is used",
         title="Every idea is shown twice",
         cols=[dict(head="Once — in isolation",
                    code="let title: String\nlet rating: Double",
                    items=["the idea, nothing in the way"]),
               dict(head="Again — inside a working app",
                    code="struct Movie: Codable {\n    let title: String\n    let tmdbID: Int?\n}",
                    items=["what it looks like in a real product"])]),
    dict(layout="stats", kicker="Nothing about the example app is special",
         title="Why it's good for teaching",
         stats=[("137", "Swift source files", "MVVM · Domain · Persistence"),
                ("0", "third-party libraries", "100% native Apple frameworks"),
                ("0", "backend servers", "runs entirely on the device")]),
    dict(layout="statement", title="Where does this idea fit in the thing I want to make?",
         sub="The useful question isn't \"how do I build this screen?\""),
    dict(layout="points", kicker="Recap", title="Course introduction",
         items=["Seven technical modules, then three craft chapters",
                "A Mac, Xcode and a free Apple account — no iPhone needed",
                "Every idea shown twice: in isolation, then in a working app",
                "The example app is scaffolding — build something of your own",
                "Do the exercises; that's where it becomes yours"]),
    dict(layout="statement", title="Module 1 — iOS Fundamentals and Swift Basics",
         sub="Install the tools, create a first project, and the Swift foundations."),
]

# ---------------------------------------------------------------- Module 01
SLIDES[1] = [
    dict(layout="points", kicker="Every app, the same foundations",
         title="What every iOS app comes down to",
         items=["**A language.** Swift — one language across every Apple platform",
                "**A set of tools.** Xcode — editor, interface builder, simulator, debugger",
                "**A way of connecting.** Outlets and actions, tying screen to code"],
         image=shot("01_showings_landing.png")),
    dict(layout="points", kicker="By the end of this video you will be able to",
         title="Objectives",
         items=["Explain what iOS development is, and why this course uses UIKit",
                "Create a project and set its bundle identifier deliberately",
                "Declare values with var and let — and reach for let first",
                "Read and safely unwrap an optional",
                "Connect a control to code with an outlet and an action"]),
    dict(layout="chips", kicker="Apple's platforms", title="What you build for",
         chips=[("iPhone", "iOS"), ("iPad", "iPadOS"),
                ("Apple Watch", "watchOS"), ("Apple TV", "tvOS")]),
    dict(layout="table", kicker="How the language got here", title="A little history",
         rows=[("before 2014", "Objective-C — still in older codebases"),
               ("2 June 2014", "Swift announced — the language this course uses"),
               ("2019", "SwiftUI — a declarative way to build interfaces")]),
    dict(layout="compare", kicker="Why UIKit first", title="UIKit, not SwiftUI",
         cols=[dict(head="UIKit",
                    items=["The overwhelming majority of existing production code",
                           "You lay things out by hand"]),
               dict(head="SwiftUI",
                    items=["Newer, declarative",
                           "A great deal is done for you"])],
         verdict="You'll understand what's being done for you — because you'll have done it yourself."),
    dict(layout="chips", kicker="What you need", title="Xcode is the whole toolkit",
         chips=[("editor", ""), ("interface builder", ""),
                ("simulator", ""), ("debugger", "")]),
    dict(layout="table", kicker="New project", title="The template asks for several things",
         rows=[("Product Name", "CineSeat"), ("Bundle Identifier", "← don't rush this"),
               ("Interface", "← or this"), ("Language", "Swift"),
               ("Storage", "None")]),
    dict(layout="code", kicker="1 — the bundle identifier",
         title="Your app's unique identity on the App Store",
         code="SevenSeven.CineSeat\n\n// your organisation, reversed  ·  your app\n// no two apps can share one",
         note="Transferable only by agreement between accounts — never simply claimed."),
    dict(layout="compare", kicker="2 — interface", title="Choose Storyboard",
         cols=[dict(head="Storyboard", ok=True, items=["this is what selects UIKit"]),
               dict(head="SwiftUI", items=["not this course"])]),
    dict(layout="table", kicker="What Xcode generates", title="Don't delete any of them",
         rows=[("AppDelegate.swift", "the first thing that runs"),
               ("SceneDelegate.swift", "window / scene lifecycle"),
               ("Main.storyboard", "your screens"),
               ("ViewController.swift", "the code behind the first screen")]),
    dict(layout="compare", kicker="Declaring a value", title="var and let",
         cols=[dict(head="var — a variable",
                    code="var score = 10\nscore = 25   // fine",
                    items=["it can change"]),
               dict(head="let — a constant", ok=True,
                    code="let age = 25\nage = 30     // error",
                    items=["once it's set, that's it"])]),
    dict(layout="code", kicker="The rule", title="Reach for let by default",
         code="let age = 25\nage = 30\n// error: cannot assign to value — 'age' is a 'let' constant",
         note="A constant is a promise that this thing will not move."),
    dict(layout="chips", kicker="The core types", title="What you'll use constantly",
         chips=[("Int", "whole numbers"), ("Double", "decimals"),
                ("String", "text"), ("Bool", "true / false"),
                ("Array", "ordered, by index"), ("Dictionary", "key / value")]),
    dict(layout="code", kicker="Control flow", title="Conventional, with one difference",
         code="if score > 20 {\n    print(\"high\")\n} else {\n    print(\"low\")\n}\n\nfor movie in movies { ... }",
         note="Swift doesn't need parentheses around the condition."),
    dict(layout="compare", kicker="Functions", title="func, a name, parameters, a return type",
         cols=[dict(head="Idiomatic Swift", ok=True,
                    code="func bookSeat(row: Int) -> Booking\nisNowPlaying\nposterURLString",
                    items=["camelCase — first word lowercase"]),
               dict(head="Not Swift", warn=True,
                    code="func book_seat(row: Int)\nis_now_playing",
                    items=["snake_case with underscores"])]),
    dict(layout="statement", title="Optionals",
         sub="The single most important idea in this module."),
    dict(layout="code", kicker="From the real app", title="Three properties can be empty",
         file="CineSeat/Models/Movies/Movie.swift",
         code="struct Movie: Codable, Equatable {\n    let title: String\n    let tmdbID: Int?\n    let genre: String\n    let rating: Double\n    let posterURLString: String?\n    let localPosterName: String?\n}",
         size=24,
         note="A ? means: this might hold a value, or it might be empty."),
    dict(layout="compare", kicker="Why optionals exist", title="Most crashes come from data",
         cols=[dict(head="Without optionals", warn=True,
                    code="poster = json[\"poster\"]\nimageView.load(poster)",
                    items=["the field isn't there", "nothing checks",
                           "the app dies in someone's hand"]),
               dict(head="With optionals", ok=True,
                    code="let poster: String? = json[\"poster\"]\nif let poster { load(poster) }",
                    items=["the compiler makes you handle it",
                           "caught at write time, not in production"])]),
    dict(layout="code", kicker="Opening an optional safely", title="Three ways",
         code="if let poster = movie.posterURLString {\n    imageView.load(poster)\n}\n\nlet name = movie.localPosterName ?? \"placeholder\"\n\nguard let id = movie.tmdbID else { return }",
         size=24,
         note="if let · ?? supplies a fallback · guard exits early"),
    dict(layout="compare", kicker="And the one to use sparingly", title="Force-unwrap",
         cols=[dict(head="You were right", ok=True,
                    items=["nothing happens — this time"]),
               dict(head="You were wrong", warn=True,
                    items=["the app crashes, in someone's hand"])],
         verdict="Every force-unwrap is a small bet that you're right."),
    dict(layout="compare", kicker="Two more language pieces", title="struct and class",
         cols=[dict(head="struct — a value type",
                    items=["it gets copied", "two independent values",
                           "use for data and models"]),
               dict(head="class — a reference type",
                    items=["it gets shared", "one object, two names",
                           "use for behaviour and services"])]),
    dict(layout="code", kicker="A protocol is a contract",
         title="What a type must do, not how",
         code="protocol BookingStore {\n    func save(_ booking: Booking)\n    func load() -> [Booking]\n}",
         note="In Module 6 this becomes the backbone of the whole architecture."),
    dict(layout="statement", title="How does a button on screen run your code?",
         sub="The last topic, and the practical one."),
    dict(layout="compare", kicker="Two separate connections", title="You usually need both",
         cols=[dict(head="Outlet",
                    code="@IBOutlet weak var confirmButton: UIButton!",
                    items=["the control as an object",
                           "enable it, restyle it, read its text"]),
               dict(head="Action",
                    code="@IBAction func confirmTapped(_ sender: UIButton)",
                    items=["the behaviour",
                           "code runs when it's tapped"])]),
    None,   # beat 25 — the ctrl-drag animation (shot 1.6)
    dict(layout="shot", kicker="All of it, doing real work",
         title="Every row in this list is one Movie struct",
         images=[shot("02_movies_list.png")],
         items=["The optional properties are the poster and the online-database ID",
                "Not every film has either",
                "The list scrolls, nothing crashes",
                "No value is forced open anywhere"]),
    dict(layout="points", kicker="Recap", title="iOS Fundamentals and Swift Basics",
         items=["iOS development means Swift and Xcode — this course uses UIKit",
                "The bundle identifier is a permanent, unique identity",
                "let by default; var only when the value must change",
                "An optional says a value might be missing — unwrap it safely",
                "Outlets connect the object; actions connect the behaviour"]),
    dict(layout="steps", kicker="Practice exercise", title="Model something you actually use",
         items=["Write a struct for it — at least six properties",
                "Make two of them optional, and be able to say why",
                "Print a summary using if let and ?? — no force-unwraps"]),
    dict(layout="statement", title="Module 2 — UIKit, MVVM, Auto Layout and Table Views",
         sub="Layout, navigation, table views, and the pattern that keeps code from becoming a mess."),
]

# ---------------------------------------------------------------- module meta
META = {
    0:  ("Course Introduction", "Eleven sessions, from no Swift to an app of your own"),
    1:  ("iOS Fundamentals and Swift Basics", "The language, the tools, and connecting screen to code"),
    2:  ("UIKit, MVVM, Auto Layout and Table Views", "Building an interface you can touch"),
    3:  ("Intermediate Swift and Concurrency", "Closures, collections, concurrency — and planning an app"),
    4:  ("Networking", "Talking to a server safely, without blocking the interface"),
    5:  ("Data Persistence and Security", "Storing data on device, and storing secrets properly"),
    6:  ("Architecture Patterns and Dependency Injection", "Keeping a growing app maintainable"),
    7:  ("Maps, Location, Notifications, Media and Animation", "The device capabilities that make an app feel native"),
    8:  ("Case Study — Building a Complete App", "Assembling seven modules into one product"),
    9:  ("Testing", "Proving it works, and why architecture made it possible"),
    10: ("Documentation Best Practices", "What makes your work survivable by somebody else"),
}

for _n, (_t, _s) in META.items():
    MODULES[_n] = dict(title=_t, sub=_s, beats=SLIDES.get(_n, []))

# ---------------------------------------------------------------- Module 02
SLIDES[2] = [
    dict(layout="points", kicker="From a language to something you can touch",
         title="This is the longest module in the course",
         items=["**Module 01 gave you a language.** Types, optionals, functions",
                "**Module 02 builds an interface.** Screens, layout, navigation, lists",
                "**This is where it starts to feel like real app development.**"],
         image=shot("02_movies_list.png")),
    dict(layout="points", kicker="By the end of this video you will be able to",
         title="Objectives",
         items=["Explain what UIKit is and how a view controller's life cycle works",
                "Apply the MVVM pattern to keep logic out of your screens",
                "Build layouts with Auto Layout constraints and stack views",
                "Navigate between screens with push and modal presentation",
                "Populate a table view using its delegate and data source"]),
    dict(layout="points", kicker="UIKit", title="Apple's long-established interface framework",
         items=["**Views.** What is actually on screen",
                "**View controllers.** The code behind one screen",
                "**An event-driven model.** The user acts, your code responds",
                "**Storyboards.** A visual file where you drag controls onto a canvas"]),
    dict(layout="statement", title="Where does your code go?",
         sub="This is where most beginner projects go wrong."),
    dict(layout="table", kicker="MVVM", title="Three responsibilities",
         rows=[("Model", "Holds data — Movie"),
               ("ViewModel", "Owns logic and formatting — MoviesViewModel"),
               ("View", "Displays only what it is handed — MoviesViewController")]),
    dict(layout="code", kicker="A real view model from the app",
         title="All the logic lives here",
         file="CineSeat/ViewModel/MoviesViewModels.swift",
         code="var filteredMovies: [Movie] {\n    movies.filter { movie in\n        let matchesSearch = searchText.isEmpty ||\n            movie.title.localizedCaseInsensitiveContains(searchText)\n        let matchesCategory = selectedCategory == .all ||\n            movie.category == selectedCategory\n        return matchesSearch && matchesCategory\n    }\n}",
         pptsize=12,
         note="Search filtering, category filtering, rating sort — none of it in the view controller."),
    dict(layout="compare", kicker="Why bother", title="Two reasons",
         cols=[dict(head="The view controller stays small",
                    items=["Instead of becoming a dumping ground for everything",
                           "Readable at a glance"]),
               dict(head="Logic in a view model can be tested", ok=True,
                    items=["Logic buried inside a screen cannot",
                           "We prove exactly this in Chapter 9"])]),
    dict(layout="points", kicker="The rule for the rest of the course",
         title="Nothing but display in the view",
         items=["**No data handling** in the view",
                "**No parsing** in the view",
                "**No network calls** in the view",
                "**All of it goes in the view model.**"]),
    dict(layout="table", kicker="The view controller life cycle",
         title="A fixed sequence, every screen",
         rows=[("viewDidLoad", "Runs once, when the screen first loads"),
               ("viewWillAppear", "Runs every time the screen is about to show"),
               ("viewDidAppear", "After it is on screen"),
               ("viewWillDisappear", "As it goes away")]),
    dict(layout="compare", kicker="The two you will use constantly",
         title="Setup versus fresh data",
         cols=[dict(head="viewDidLoad — once",
                    code="override func viewDidLoad() {\n    super.viewDidLoad()\n    tableView.dataSource = self\n}",
                    items=["Setup goes here"]),
               dict(head="viewWillAppear — every time",
                    code="override func viewWillAppear(_ a: Bool) {\n    super.viewWillAppear(a)\n    reloadBookings()\n}",
                    items=["Fresh data each time the user returns"])],
         verdict="Putting it in the wrong place is a classic source of stale-data bugs."),
    dict(layout="statement", title="Auto Layout",
         sub="The part almost everyone finds hardest. If you struggle here, you are exactly where everybody else is."),
    dict(layout="stats", kicker="Why constraints exist", title="One design, many screens",
         stats=[("1", "iPhone size, originally", "layout was trivial"),
                ("5+", "sizes today", "SE · standard · Pro · Max · iPad"),
                ("1", "system that scales", "constraints")]),
    dict(layout="points", kicker="Two pieces of vocabulary", title="Origin, leading and trailing",
         items=["**The origin.** Zero, zero is the top-left corner",
                "**Leading and trailing**, not left and right",
                "**They follow reading direction**, so the same layout works right-to-left",
                "You change nothing to support Arabic or Hebrew"]),
    dict(layout="shot", kicker="The technique that makes constraints manageable",
         title="Stack views",
         images=[shot("07_seat_map.png")],
         items=["**This seat map** is rows of seats inside a vertical stack",
                "**Constrain the stack**, not every individual seat button",
                "**One set of constraints** instead of dozens",
                "It handles what is inside for you"]),
    dict(layout="steps", kicker="If you get stuck", title="Do not let constraints block you",
         items=["Build the working flow first",
                "Treat layout polish as a finishing pass",
                "Group things into stacks before you start constraining"]),
    dict(layout="statement", title="Moving between screens",
         sub="Three ways — two of them worth using."),
    dict(layout="compare", kicker="The two worth using", title="Push and modal",
         cols=[dict(head="Push navigation",
                    items=["Slides in from the right",
                           "Gives you a back button automatically",
                           "For going deeper into a hierarchy"]),
               dict(head="Modal presentation",
                    items=["Slides up from the bottom, sits on top",
                           "Good for an about screen or a dialog"])]),
    dict(layout="compare", kicker="The third way", title="Segues constrain you",
         cols=[dict(head="A segue cannot jump", warn=True,
                    items=["Drawn in the storyboard, no code",
                           "Forces you through the hierarchy",
                           "Five screens deep, it cannot jump back to screen two"]),
               dict(head="Code can", ok=True,
                    items=["Navigation in code goes anywhere",
                           "This is why the course does it in code"])]),
    dict(layout="code", kicker="One gotcha that will cost you an afternoon",
         title="Push does nothing outside a navigation controller",
         code="navigationController?.pushViewController(detail, animated: true)\n\n// the code is correct\n// the button does nothing\n// there is no error message",
         note="If that happens to you — the screen is not inside a navigation controller."),
    dict(layout="compare", kicker="Finally, table views", title="Table or collection?",
         cols=[dict(head="Table view",
                    items=["A single scrolling column of rows",
                           "Like a social media feed",
                           "Far more common — our focus"]),
               dict(head="Collection view",
                    items=["A grid of tiles", "Like a photo gallery"])]),
    dict(layout="code", kicker="Two protocols make a table view work",
         title="Data source and delegate",
         code="tableView.dataSource = self   // how many rows, what is in each\ntableView.delegate   = self   // what happens when a row is tapped",
         note="You assign both in viewDidLoad."),
    dict(layout="statement", title="Miss that assignment and the table renders completely empty",
         sub="No crash, no warning, no error. Probably the single most common beginner stumble in UIKit."),
    dict(layout="code", kicker="One more detail in the cell", title="prepareForReuse",
         code="override func prepareForReuse() {\n    super.prepareForReuse()\n    posterImageView.image = nil\n}",
         note="Cells are recycled as you scroll — clearing on reuse prevents the previous row's image flickering in."),
    dict(layout="shot", kicker="The whole module, on screen at once",
         title="The screen is not doing the work",
         images=[shot("02_movies_list.png"), shot("03_movie_detail.png")],
         items=["**Search and sort** ask the view model for a filtered, sorted list",
                "**Rows are reusable cells** built from stack views",
                "**Navigation** pushes the detail screen in code",
                "**viewDidLoad** wired it all together"]),
    dict(layout="points", kicker="Recap", title="UIKit, MVVM, Auto Layout and Table Views",
         items=["UIKit is views, view controllers and an event-driven model",
                "MVVM keeps logic in the view model — and testable",
                "viewDidLoad runs once; viewWillAppear runs every time",
                "Constraints scale one design across devices; stack views tame them",
                "A table view needs both its data source and its delegate assigned"]),
    dict(layout="steps", kicker="Practice exercise", title="Build a two-screen list app",
         items=["A table view listing something you care about, driven by a view model",
                "Tap a row to push a detail screen — in code, no segues",
                "Lay the detail screen out with stack views, not individual constraints"]),
    dict(layout="statement", title="Module 3 — Intermediate Swift and Concurrency",
         sub="Closures, collections and concurrency — then how to plan an app before you write it."),
]
MODULES[2]["beats"] = SLIDES[2]

# ---------------------------------------------------------------- Module 03
SLIDES[3] = [
    dict(layout="statement", title="The shortest module, and the most conceptually demanding",
         sub="The language features that separate code that works from code that holds up."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Pass behaviour around with closures, and know escaping from non-escaping",
                "Use map, filter and reduce for what each actually does",
                "Explain ARC, weak references and retain cycles",
                "Keep long work off the main thread with async and await",
                "Plan an app before writing it, in four steps"]),
    dict(layout="code", kicker="Closures", title="A block of code you can pass around like a value",
         code="let sorted = movies.sorted { first, second in\n    first.rating > second.rating\n}",
         note="If you wrote a computed property last module, you have already written one."),
    dict(layout="compare", kicker="A distinction worth knowing", title="Escaping or non-escaping",
         cols=[dict(head="Non-escaping",
                    items=["Runs and finishes inside the function",
                           "The default"]),
               dict(head="@escaping",
                    items=["Outlives the function call",
                           "Stored, or run later — network callbacks"])]),
    dict(layout="statement", title="Do slow work synchronously and the interface freezes",
         sub="The user thinks your app has hung. Escaping, asynchronous work is how you avoid it."),
    dict(layout="statement", title="Three operations you will reach for constantly",
         sub="These get confused, so be precise about what each one does."),
    dict(layout="code", kicker="map", title="Transforms — same length out",
         code="let titles = movies.map { $0.title }\n// [Movie]  ->  [String], one for one",
         note="It transforms. It does not search."),
    dict(layout="code", kicker="filter", title="Selects — shorter collection out",
         code="let showing = movies.filter { $0.isNowPlaying }\n// keeps only the elements matching the condition",
         note="It selects."),
    dict(layout="code", kicker="reduce", title="Collapses — one value out",
         code="let total = seats.reduce(0) { sum, seat in sum + seat.price }\n// folds a whole collection down to a single value",
         note="It collapses."),
    dict(layout="code", kicker="And if you want to find something", title="first(where:) is the fourth operation",
         code="let match = movies.first(where: { $0.tmdbID == id })",
         note="Mixing up map and search is a common source of slow, wrong code."),
    dict(layout="code", kicker="Doing real work", title="Two operations, chained",
         code="movies\n    .filter { $0.title.localizedCaseInsensitiveContains(searchText) }\n    .sorted { $0.rating > $1.rating }",
         note="Replacing what would have been a nested loop."),
    dict(layout="points", kicker="Memory", title="Automatic Reference Counting",
         items=["**ARC counts** how many things are holding an object",
                "**When nothing holds it**, the object is freed",
                "**You do not free memory by hand** — but you do decide who holds what"]),
    dict(layout="table", kicker="Three kinds of reference", title="Who keeps an object alive",
         rows=[("strong", "Keeps the object alive — the default"),
               ("weak", "Does not keep it alive; set to nil automatically when it goes"),
               ("unowned", "Like weak, but assumes it is still there — crashes if wrong")]),
    dict(layout="statement", title="A retain cycle is two objects each holding the other strongly",
         sub="Neither can ever be freed. That is a leak."),
    dict(layout="code", kicker="One habit prevents most of them", title="weak self by default",
         code="fetchMovies { [weak self] result in\n    guard let self else { return }\n    self.reload(result)\n}",
         note="It costs nothing when unnecessary, and saves you when it matters."),
    dict(layout="statement", title="Background threads do the waiting. The main thread does the drawing.",
         sub="There is one rule in concurrency, and everything follows from it."),
    dict(layout="compare", kicker="Where work belongs", title="Off the main thread, back for the UI",
         cols=[dict(head="Background", items=["Fetching data", "Downloading images", "Decoding JSON"]),
               dict(head="Main thread", ok=True,
                    items=["Every single UI update", "Without exception"])]),
    dict(layout="compare", kicker="Two generations of the same idea", title="GCD and async / await",
         cols=[dict(head="Grand Central Dispatch",
                    code="DispatchQueue.global().async {\n    // work\n    DispatchQueue.main.async { ... }\n}",
                    items=["The older way — you will meet it in existing code"]),
               dict(head="async / await", ok=True,
                    code="let movies = try await api.fetchMovies()",
                    items=["await means: pause here, let others run, resume when ready"])]),
    dict(layout="statement", title="Before you build anything real, you plan it",
         sub="The part of this module that is not code."),
    dict(layout="steps", kicker="A four-step workflow", title="Worth adopting",
         items=["Requirements — list every feature, unfiltered",
                "Flowchart — turn those into paths and decisions",
                "Wireframe — sketch what each screen holds, not how it looks",
                "Then build"]),
    dict(layout="points", kicker="The flowchart for the reference app",
         title="What is interesting is not the happy path",
         items=["**Not signed in.** Route to account creation",
                "**No seat selected.** Route to a validation alert",
                "**Cancelled.** Release the seats, cancel the pending reminder",
                "**Most of real app design** is the handling of things going wrong"]),
    dict(layout="statement", title="When your app gets tested, every path gets walked",
         sub="Including the awkward ones. If you already mapped them, testing confirms rather than discovers."),
    dict(layout="points", kicker="Recap", title="Intermediate Swift and Concurrency",
         items=["Closures pass behaviour around; escaping ones outlive the call",
                "map transforms, filter selects, reduce collapses, first(where:) finds",
                "ARC frees what nothing holds — weak self breaks retain cycles",
                "Background threads wait; the main thread draws",
                "Plan in four steps before you write code"]),
    dict(layout="steps", kicker="Practice exercise", title="Plan, then transform",
         items=["Write requirements and a flowchart for an app you want to build",
                "Include at least three failure branches, not just the happy path",
                "Then take a list in code and chain filter and sorted over it"]),
    dict(layout="statement", title="Module 4 — Networking",
         sub="The app starts talking to the internet: URLSession, JSON, and a real public API."),
]
MODULES[3]["beats"] = SLIDES[3]

# ---------------------------------------------------------------- Module 04
SLIDES[4] = [
    dict(layout="statement", title="Almost every app worth using talks to a server",
         sub="Safely, without freezing, and without shipping your secrets to strangers."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Make a request with URLSession using async and await",
                "Check the status code before trusting the data",
                "Decode JSON into Swift types with Codable",
                "Centralise networking behind one API client",
                "Keep credentials out of your source code"]),
    dict(layout="points", kicker="Networking on iOS", title="HTTP, in practice always HTTPS",
         items=["**URLSession** is Apple's built-in API for it",
                "**You do not need a third-party library** for this",
                "**Everything in this module** uses only what ships with the platform"]),
    dict(layout="compare", kicker="The methods you will use", title="GET and POST",
         cols=[dict(head="GET", items=["Fetches", "You send nothing, you get data back"]),
               dict(head="POST", items=["Sends data and receives a response",
                                        "Logging in is the obvious example"])]),
    dict(layout="statement", title="Every request has the same shape",
         sub="Build a URL, set any headers, make the call, check the response, decode."),
    dict(layout="code", kicker="Building the request", title="URL, then URLRequest for headers",
         code="guard let url = URL(string: base + \"/movie/\\(id)/reviews\") else { return }\n\nvar request = URLRequest(url: url)\nrequest.setValue(\"Bearer \\(token)\", forHTTPHeaderField: \"Authorization\")",
         pptsize=12,
         note="A plain GET can skip URLRequest entirely."),
    dict(layout="code", kicker="The call", title="async and await, from the last module",
         code="let (data, response) = try await URLSession.shared.data(for: request)",
         note="The interface stays responsive while it waits."),
    dict(layout="statement", title="Check the status code before you touch the data",
         sub="This is the step people skip, and it is the important one."),
    dict(layout="table", kicker="A request can succeed and still contain nothing useful",
         title="What the codes mean",
         rows=[("200", "OK"), ("401", "You are not authenticated"),
               ("404", "There is nothing at that address"),
               ("500", "The server itself failed")]),
    dict(layout="code", kicker="Notice what is absent", title="No force-unwrapping anywhere",
         code="guard let http = response as? HTTPURLResponse,\n      (200..<300).contains(http.statusCode) else {\n    throw APIError.badStatus\n}",
         note="Every uncertain value is guarded. The worst case is an error you handle, not a crash."),
    dict(layout="code", kicker="Turning data into Swift types", title="Codable does it in one line",
         code="struct Review: Codable {\n    let author: String\n    let content: String\n}\n\nlet reviews = try JSONDecoder().decode([Review].self, from: data)",
         pptsize=12),
    dict(layout="compare", kicker="Why this matters", title="Before and after Codable",
         cols=[dict(head="The old approach", warn=True,
                    items=["Pull values out of a dictionary key by key",
                           "The code grew forever as the payload did"]),
               dict(head="Codable", ok=True,
                    items=["One line, whatever the shape",
                           "The compiler checks it for you"])]),
    dict(layout="code", kicker="One wrinkle", title="CodingKeys bridges naming styles",
         code="struct Movie: Codable {\n    let posterPath: String?\n    enum CodingKeys: String, CodingKey {\n        case posterPath = \"poster_path\"\n    }\n}",
         pptsize=12,
         note="Swift uses camelCase; plenty of APIs use snake_case. You keep idiomatic Swift names."),
    dict(layout="code", kicker="Rather than repeat this in every screen", title="One generic API client",
         code="func fetch<T: Decodable>(_ path: String) async throws -> T {\n    let (data, response) = try await session.data(for: request(path))\n    try validate(response)\n    return try JSONDecoder().decode(T.self, from: data)\n}",
         pptsize=11,
         note="One function serves every endpoint in the app."),
    dict(layout="statement", title="Keep your base URLs in one constant",
         sub="Not scattered through view controllers — switching development to production becomes one edit."),
    dict(layout="shot", kicker="Here it is running", title="Two sources, never mixed",
         images=[shot("04_reviews_ticketplease.png"), shot("05_reviews_online_tmdb.png")],
         items=["**The app's own reviews** are stored on the device",
                "**The Online tab** fetches from a real public API",
                "**Same screen**, two very different data paths"]),
    dict(layout="statement", title="External reviews are never counted into the app's own rating",
         sub="Averaging someone else's numbers into yours would make both meaningless."),
    dict(layout="points", kicker="Credentials", title="The token is not in the source code",
         items=["**Not in the repository.** It lives only in a local scheme setting",
                "**Not in the bundle.** Anything you ship can be extracted from it",
                "**A production app keeps secrets on a server**, not in the app"]),
    dict(layout="statement", title="Anything you ship inside an app can be extracted from it",
         sub="Getting into that habit now costs nothing and prevents a real incident later."),
    dict(layout="points", kicker="Recap", title="Networking",
         items=["URLSession with async and await — no third-party library needed",
                "Always check the status code before trusting the data",
                "Codable turns JSON into Swift types in one line",
                "Centralise requests behind one generic API client",
                "Secrets never live in source, the repo, or the shipped bundle"]),
    dict(layout="steps", kicker="Practice exercise", title="Talk to a real API",
         items=["Pick a free public API and fetch one endpoint with async / await",
                "Decode it into a Codable struct — handle a non-200 status explicitly",
                "Keep the base URL in one constant and the key out of source control"]),
    dict(layout="statement", title="Module 5 — Data Persistence and Security",
         sub="The data has arrived. Where does it live when the app closes?"),
]
MODULES[4]["beats"] = SLIDES[4]

# ---------------------------------------------------------------- Module 05
SLIDES[5] = [
    dict(layout="statement", title="Close the app, reopen it, and everything's gone",
         sub="This module is about memory — and the one storage decision that, got wrong, is a real security problem."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Choose between UserDefaults, files, Core Data and the Keychain",
                "Persist models as JSON with Codable and FileManager",
                "Explain why UserDefaults is not a safe place for secrets",
                "Store credentials in the Keychain, correctly scoped"]),
    dict(layout="statement", title="There is no single right answer",
         sub="iOS gives you several mechanisms deliberately. The skill is matching each to the weight and sensitivity of the data."),
    dict(layout="code", kicker="First — UserDefaults", title="Small, lightweight key-value storage",
         code="UserDefaults.standard.set(true, forKey: \"isDarkMode\")\nlet dark = UserDefaults.standard.bool(forKey: \"isDarkMode\")",
         note="Which filter was last selected. Whether the user has seen the welcome screen."),
    dict(layout="points", kicker="One rule", title="The type must match",
         items=["**Save a Bool, read a String** and you get an error",
                "**A naming habit that prevents it:** prefix boolean keys with `is`",
                "`isDarkMode`, `isNowPlaying`, `isFirstLaunch`"]),
    dict(layout="code", kicker="Second — FileManager", title="Bigger, structured data as JSON",
         code="let url = FileManager.default\n    .urls(for: .documentDirectory, in: .userDomainMask)[0]\n    .appendingPathComponent(\"bookings.json\")\n\ntry JSONEncoder().encode(bookings).write(to: url)",
         pptsize=12),
    dict(layout="points", kicker="This is how the reference app stores its data",
         title="Codable in, Codable out",
         items=["**Bookings, profiles and reviews** all live as JSON files",
                "**Codable turns the model into JSON**, FileManager writes it",
                "**On next launch it reads straight back** into the same Swift types"]),
    dict(layout="compare", kicker="Third — Core Data", title="Apple's heavyweight option",
         cols=[dict(head="Reach for it when",
                    items=["You have a lot of data",
                           "Complex relationships between entities",
                           "You need querying, not just loading"]),
               dict(head="The reference app does not use it",
                    items=["For this volume, JSON files were simpler",
                           "Easier to reason about"])]),
    dict(layout="statement", title="That is a real skills gap, stated honestly",
         sub="Core Data is worth learning next — the app simply did not need it."),
    dict(layout="statement", title="The Keychain",
         sub="The fourth mechanism, and the most important part of this module."),
    dict(layout="compare", kicker="A belief that circulates", title="UserDefaults is NOT encrypted",
         cols=[dict(head="What people believe", warn=True,
                    items=["\"UserDefaults is encrypted on iOS\"",
                           "\"So it's fine for passwords and tokens\"",
                           "That is not true"]),
               dict(head="What actually happens", warn=True,
                    items=["A plain, unencrypted file in your app's container",
                           "No access control",
                           "Readable with file system access or an unencrypted backup"])]),
    dict(layout="table", kicker="Match the store to the data", title="Where things belong",
         rows=[("UserDefaults", "Preferences and flags — nothing sensitive"),
               ("JSON files", "Models: bookings, profiles, reviews"),
               ("Core Data", "Large, related, queryable data sets"),
               ("Keychain", "Passwords, tokens, API keys, anything personal")]),
    dict(layout="statement", title="Passwords, tokens, API keys — those go in the Keychain",
         sub="Encrypted and protected by the operating system itself."),
    dict(layout="code", kicker="The real implementation", title="Note the accessibility setting",
         code="let query: [String: Any] = [\n    kSecClass as String: kSecClassGenericPassword,\n    kSecAttrAccount as String: email,\n    kSecvalueData as String: passwordData,\n    kSecAttrAccessible as String:\n        kSecAttrAccessibleWhenUnlockedThisDeviceOnly\n]",
         pptsize=11,
         note="'This device only' means the credential never travels in an iCloud backup."),
    dict(layout="statement", title="Whatever encoding you save with, you must read back with",
         sub="Mismatched text encodings are a confusing Keychain bug that will cost you an afternoon."),
    dict(layout="shot", kicker="Persistence, proven", title="Confirm a booking, then close the app completely",
         images=[shot("09_booking_confirmation.png")],
         items=["**Not backgrounded — closed.**",
                "**Then reopen it**",
                "The booking is still there, with the same ID"]),
    dict(layout="shot", kicker="There it is", title="Straight back from a JSON file on disk",
         images=[shot("15_bookings_list.png")],
         items=["**Decoded back** into the same Swift types it was saved from",
                "**No database**, no server, no third-party library"]),
    dict(layout="shot", kicker="And the account", title="Never in the same place, never in plain text",
         images=[shot("22_profile_account.png")],
         items=["**The profile details** are in a JSON file",
                "**The password** is in the Keychain",
                "Two different stores, chosen by sensitivity"]),
    dict(layout="points", kicker="Recap", title="Data Persistence and Security",
         items=["Match the mechanism to the weight and sensitivity of the data",
                "UserDefaults for small flags — never for secrets",
                "Codable plus FileManager persists models as JSON",
                "UserDefaults is not encrypted; the Keychain is",
                "Scope credentials to this device only"]),
    dict(layout="steps", kicker="Practice exercise", title="Make something survive a relaunch",
         items=["Persist a model as JSON with Codable and FileManager",
                "Store one credential in the Keychain, this-device-only",
                "Close the app fully, reopen, and prove both came back"]),
    dict(layout="statement", title="Module 6 — Architecture Patterns and Dependency Injection",
         sub="How to organise all of this so the app doesn't collapse under its own weight."),
]
MODULES[5]["beats"] = SLIDES[5]

# ---------------------------------------------------------------- Module 06
SLIDES[6] = [
    dict(layout="statement", title="A ten-thousand-line view controller was once worn as a badge",
         sub="There was a time when a very long file was taken as a sign of a skilled developer."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Organise a project so a stranger can find things",
                "Explain Clean Architecture's layers and the inward dependency rule",
                "Depend on protocols instead of concrete types",
                "Wire an app from a single composition root",
                "Recognise when a singleton is fine and when it is a trap"]),
    dict(layout="statement", title="How quickly could a stranger find the one piece they need to change?",
         sub="Length isn't skill. Navigability is."),
    dict(layout="table", kicker="How the reference project is organised",
         title="Each folder has one job",
         rows=[("Models", "The data types"), ("View", "View controllers and screens"),
               ("ViewModel", "Logic and formatting"), ("Domain", "Protocols — the contracts"),
               ("Persistence", "Storage, keychain, notifications"),
               ("CustomViews", "Reusable components like the seat map")]),
    dict(layout="statement", title="Massive View Controller",
         sub="In plain MVC everything ends up in the controller — data loading, parsing, formatting, navigation. This is the failure mode the structure avoids."),
    dict(layout="table", kicker="Clean Architecture", title="Three layers",
         rows=[("Presentation", "Views and view models"),
               ("Domain", "The protocols — the rules of the app"),
               ("Data", "Persistence, networking, the outside world")]),
    dict(layout="statement", title="Dependencies point inward only",
         sub="The domain layer knows nothing about UIKit, nothing about URLSession, nothing about where data comes from."),
    dict(layout="code", kicker="How that is expressed", title="The app's protocols",
         code="protocol MovieFetching {\n    func fetchMovies() async throws -> [Movie]\n}\n\nprotocol BookingManaging {\n    func add(_ booking: Booking)\n    func cancel(id: String)\n    func all() -> [Booking]\n}",
         pptsize=12),
    dict(layout="points", kicker="A protocol is a contract", title="What, never how",
         items=["**MovieFetching** says: whatever you are, you can give me movies",
                "**BookingManaging** says: you can add, cancel and list bookings",
                "**Neither says** where the data lives or how it gets there"]),
    dict(layout="statement", title="Every view model depends on protocols — not on a concrete store",
         sub="Not on a specific API client. Just the contract."),
    dict(layout="statement", title="That is dependency injection",
         sub="The consumer declares what it needs. Something else decides what it gets. It is the most valuable structural idea in this course."),
    dict(layout="code", kicker="And that something else is the composition root",
         title="The one place concrete types are chosen",
         code="enum AppFactory {\n    static func makeMoviesViewModel() -> MoviesViewModel {\n        MoviesViewModel(fetcher: LocalMovieStore(),\n                        bookings: FileBookingStore())\n    }\n}",
         pptsize=12,
         note="Every screen is built here. Nothing else constructs its own dependencies."),
    dict(layout="statement", title="To swap local JSON for a real backend, you change this one file",
         sub="Not a single view model changes. That is the payoff."),
    dict(layout="table", kicker="Three injection patterns in play", title="When to use which",
         rows=[("Singleton", "One shared instance — the settings store"),
               ("Protocol injection", "Anything a test needs to replace"),
               ("Composition root", "Where the concrete choices are made")]),
    dict(layout="compare", kicker="A word on singletons", title="Half the bad reputation is deserved",
         cols=[dict(head="The problem is not the single instance",
                    items=["One shared settings store is fine"]),
               dict(head="The problem is reaching for it everywhere", warn=True,
                    items=["Hidden dependencies you cannot see in a signature",
                           "And cannot replace in a test"])]),
    dict(layout="shot", kicker="One more structural benefit", title="Reusable custom views",
         images=[shot("07_seat_map.png")],
         items=["**This seat map is not a stock UIKit control**",
                "**Built from vertical rows of horizontal stacks**",
                "**Written once**, used in more than one place"]),
    dict(layout="statement", title="Shared formatting is the related problem",
         sub="The same rating appears on the list, the detail screen and the booking. Format it in three places and they will drift apart."),
    dict(layout="shot", kicker="The reuse, in action", title="One component, two modes",
         images=[shot("07_seat_map.png"), shot("16_booking_detail.png")],
         items=["**Interactive**, letting you pick seats",
                "**And read-only** inside booking detail",
                "Same component, different configuration"]),
    dict(layout="points", kicker="Recap", title="Architecture and Dependency Injection",
         items=["Navigability is the measure of quality, not brevity or length",
                "Clean Architecture layers with dependencies pointing inward",
                "Depend on protocols, never on concrete types",
                "One composition root chooses every implementation",
                "Reusable views and shared formatters stop drift"]),
    dict(layout="steps", kicker="Practice exercise", title="Invert one dependency",
         items=["Take a screen that builds its own data source",
                "Extract a protocol for what it actually needs",
                "Build it from a composition root, and swap in a fake implementation"]),
    dict(layout="statement", title="Module 7 — Maps, Location, Notifications, Media and Animation",
         sub="The last technical module: the device capabilities that make an app feel native."),
]
MODULES[6]["beats"] = SLIDES[6]

# ---------------------------------------------------------------- Module 07
SLIDES[7] = [
    dict(layout="statement", title="What makes an app feel like it belongs on a phone",
         sub="Rather than like a website in a frame. It knows where it is. It can reach you when it isn't open."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Show a map with real pins using MapKit",
                "Request a permission correctly — in code and in Info.plist",
                "Schedule a local notification, and know when you need a server",
                "Pick the right photo API, and animate a change with intent"]),
    dict(layout="compare", kicker="A distinction that saves confusion", title="MapKit and Core Location",
         cols=[dict(head="MapKit", items=["The map itself", "What you see and interact with",
                                          "Pins, regions, callouts"]),
               dict(head="Core Location", items=["Where the device is",
                                                 "GPS, permissions, updates"])]),
    dict(layout="points", kicker="A map needs three things", title="Centre, region, annotations",
         items=["**A coordinate** to centre on",
                "**A region** defining how far out you are zoomed",
                "**Annotations** for your pins",
                "Add a delegate and you can respond to taps"]),
    dict(layout="compare", kicker="One decision", title="MapKit or the Google Maps SDK",
         cols=[dict(head="Google Maps SDK",
                    items=["Richer place data", "Phone numbers, opening hours",
                           "Needs an API key and a dependency"]),
               dict(head="MapKit", ok=True,
                    items=["Native, no API key, no dependency",
                           "Enough for showing your own locations"])]),
    dict(layout="statement", title="Permissions are where people lose hours",
         sub="Anything touching location, camera or photos needs two things — and everybody remembers only the first."),
    dict(layout="compare", kicker="Both are required", title="Code and Info.plist",
         cols=[dict(head="You request it in code",
                    code="locationManager\n    .requestWhenInUseAuthorization()",
                    items=["Everybody remembers this one"]),
               dict(head="And declare it in Info.plist", warn=True,
                    items=["Skip it and the feature does not work",
                           "It fails silently, with no error"])]),
    dict(layout="table", kicker="The keys must be exact", title="Info.plist usage descriptions",
         rows=[("NSLocationWhenInUseUsageDescription", "Location, while using the app"),
               ("NSCameraUsageDescription", "Camera"),
               ("NSPhotoLibraryUsageDescription", "Photo library"),
               ("NSMicrophoneUsageDescription", "Microphone")]),
    dict(layout="statement", title="Whatever text you write is shown to the user word for word",
         sub="So write a real reason — \"used to show cinemas near you\" — not \"we need your location\"."),
    dict(layout="statement", title="Two kinds of notification",
         sub="And the difference is architectural, not cosmetic."),
    dict(layout="compare", kicker="Where they come from", title="Push and local",
         cols=[dict(head="Push — APNs",
                    items=["Sent from a server", "Needs a backend",
                           "Needs a paid developer account"]),
               dict(head="Local", ok=True,
                    items=["Scheduled on the device itself",
                           "No server, no account tier"])]),
    dict(layout="points", kicker="The reference app uses local notifications",
         title="The reasoning is practical",
         items=["**APNs needs a backend** to send from",
                "**Plus a paid Apple Developer account**",
                "**Local notifications cover the actual need:** remind me before my booking"]),
    dict(layout="statement", title="Be honest about the limitation, because it is real",
         sub="A local notification can only fire on a schedule the device already knows about. Anything reactive needs a server."),
    dict(layout="points", kicker="Two details worth copying", title="From this implementation",
         items=["**It checks a user setting first** — reminders off means nothing is scheduled",
                "**Cancelling a booking cancels its pending reminder**",
                "A notification for a booking that no longer exists is a bug users remember"]),
    dict(layout="compare", kicker="Two photo APIs, often confused", title="PHPicker and UIImagePickerController",
         cols=[dict(head="PHPicker", ok=True,
                    items=["The modern one", "What you should use to pick",
                           "No permission prompt needed to browse"]),
               dict(head="UIImagePickerController",
                    items=["Soft-deprecated since iOS 14",
                           "But PHPicker cannot take a photo",
                           "For camera capture you still need this"])]),
    dict(layout="statement", title="PHPicker cannot take a photo",
         sub="For camera capture you still reach for the older API. Know which job each one does."),
    dict(layout="code", kicker="Animation", title="The duration is the whole point",
         code="UIView.animate(withDuration: 0.3) {\n    self.seatView.alpha = 1\n    self.seatView.transform = .identity\n}",
         note="Set the duration to zero and the change snaps — which is sometimes exactly what you want."),
    dict(layout="shot", kicker="All together", title="Real pins from real coordinates",
         images=[shot("19_locations_map.png"), shot("20_pin_callout.png"),
                 shot("21_cinema_detail.png")],
         note="Tapping a pin opens a callout and routes into the cinema's details and showtimes."),
    dict(layout="points", kicker="Recap", title="Maps, Location, Notifications, Media, Animation",
         items=["MapKit is the map; Core Location is where the device is",
                "A permission needs both the code request and the Info.plist key",
                "Your usage string is shown to the user word for word",
                "Local notifications need no server; push does",
                "PHPicker to pick, the older API to capture"]),
    dict(layout="steps", kicker="Practice exercise", title="Make it feel native",
         items=["Show a map with at least three real pins and a working callout",
                "Request one permission properly, with an honest usage string",
                "Schedule a local notification, and cancel it when its reason disappears"]),
    dict(layout="statement", title="That completes the technical curriculum",
         sub="Chapter 8 assembles all seven modules into one complete application."),
]
MODULES[7]["beats"] = SLIDES[7]

# ---------------------------------------------------------------- Module 08
SLIDES[8] = [
    dict(layout="statement", title="Seven capabilities in isolation is not one product",
         sub="Assembling them is a separate skill — and it is the one interviews probe."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Turn one sentence into a requirements list",
                "Draw a flowchart that covers the failure branches, not just the happy path",
                "Recognise when to cut scope deliberately",
                "See where each module shows up in a finished product"]),
    dict(layout="statement", title="It started as one sentence",
         sub="A cinema ticket-booking app where you browse films, pick a schedule, choose seats, see the price and confirm a reservation."),
    dict(layout="table", kicker="That became a requirements list", title="Deliberately unglamorous",
         rows=[("Browse", "Movie list · movie details · showtimes"),
               ("Book", "Seat selection · booking summary · confirmation"),
               ("Manage", "Bookings history · cancellation"),
               ("Guard", "Validation alerts throughout")]),
    dict(layout="statement", title="One thing was missing, and an early review caught it",
         sub="There was no profile screen. Adding accounts unlocked roughly a third of everything else."),
    dict(layout="statement", title="Write requirements where somebody else can read and question them",
         sub="Rather than holding them in your head. That is the strongest argument for the whole exercise."),
    dict(layout="shot", kicker="The requirements became this flowchart",
         title="Rectangles are processes, diamonds are decisions",
         images=[asset("flowchart_booking.png")]),
    dict(layout="points", kicker="Trace the happy path first", title="Then look at everything else",
         items=["**Start, browse, select, confirm, done** — that is the easy part",
                "**Not signed in** routes off to account creation",
                "**No seat selected** routes to a validation alert",
                "**Cancel** releases the seats and cancels the pending reminder"]),
    dict(layout="statement", title="Most of real app design is the handling of things going wrong",
         sub="Those branches are where bugs breed. Drawing them before any code existed is why they were handled deliberately."),
    dict(layout="statement", title="Then a wireframe — what goes where, not what it looks like",
         sub="Chasing pixel-perfect visuals at that stage wastes effort on decisions that change once real content arrives."),
    dict(layout="compare", kicker="Two things changed between plan and build",
         title="Both changes were healthy",
         cols=[dict(head="The 'how to use' tab was cut",
                    items=["It existed only to fill a fourth tab",
                           "Settings made it redundant"]),
               dict(head="Payment was scoped out on purpose",
                    items=["Better to ship no payment",
                           "Than a fake one that misleads"])]),
    dict(layout="shot", kicker="Here is the result", title="Five taps to a confirmed ticket",
         images=[shot("02_movies_list.png"), shot("07_seat_map.png"),
                 shot("09_booking_confirmation.png")],
         note="Browsing a film to a confirmed, locally-persisted ticket with its own booking ID."),
    dict(layout="table", kicker="Every step is a module doing real work",
         title="Where the curriculum shows up",
         rows=[("Module 2", "The detail screen — UIKit, MVVM, table views"),
               ("Modules 4 & 5", "The data — networking and persistence"),
               ("Module 6", "The structure holding it together"),
               ("Module 7", "Maps, notifications, the native feel")]),
    dict(layout="compare", kicker="One design detail deserves its own moment",
         title="Movies book by seat. Concerts book by quantity.",
         cols=[dict(head="Two booking systems?", warn=True,
                    items=["The obvious answer", "Twice the code, twice the bugs"]),
               dict(head="One reservation core", ok=True,
                    items=["Two different front-ends",
                           "Exactly the reuse the architecture was built for"])]),
    dict(layout="shot", kicker="And here it is, working", title="The same core, two front-ends",
         images=[shot("07_seat_map.png"), shot("12_concert_quantity.png")],
         note="Clean Architecture and protocol-based injection, paying off on screen."),
    dict(layout="points", kicker="Recap", title="Building a Complete App",
         items=["One sentence becomes a requirements list somebody else can question",
                "The flowchart's value is its failure branches",
                "Wireframe what goes where, not what it looks like",
                "Cutting scope deliberately is a healthy sign, not a failure",
                "Reuse is designed in, not discovered later"]),
    dict(layout="statement", title="Chapter 9 proves it all works",
         sub="And shows why the architecture from Module 6 was worth the effort."),
]
MODULES[8]["beats"] = SLIDES[8]

# ---------------------------------------------------------------- Module 09
SLIDES[9] = [
    dict(layout="statement", title="How do you know your app works?",
         sub="Not \"it looked fine when I tried it\" — how do you know, every time, automatically?"),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Tell a unit test from a UI test, and when each earns its cost",
                "Write a test that needs no screen at all",
                "Replace real stores with fakes through protocols",
                "Name tests so the suite reads as a specification"]),
    dict(layout="compare", kicker="Two kinds", title="Unit and UI tests",
         cols=[dict(head="Unit tests", ok=True,
                    items=["Never launch the app", "Check logic directly", "Fast — milliseconds"]),
               dict(head="UI tests",
                    items=["Launch the app and drive it", "Tap, scroll, assert on screen",
                           "Slower, but they prove the whole path"])]),
    dict(layout="code", kicker="A unit test", title="Read the name, predict the body",
         code="func testMovieSearchAndRatingSortAcrossCategories() {\n    let vm = MoviesViewModel(fetcher: FakeMovieStore())\n    vm.searchText = \"dune\"\n    XCTAssertEqual(vm.filteredMovies.count, 2)\n    vm.toggleRatingSortOrder()\n    XCTAssertEqual(vm.filteredMovies.first?.title, \"Dune: Part Two\")\n}",
         pptsize=11),
    dict(layout="steps", kicker="What it actually does", title="Four steps",
         items=["Create a view model",
                "Set the search text and check the filtered result",
                "Flip the sort order",
                "Check the order changed"]),
    dict(layout="statement", title="Here is the point, and it is why Module 6 mattered",
         sub="Look at what this test does not need."),
    dict(layout="points", kicker="What is absent from that test", title="No screen at all",
         items=["**No storyboard**", "**No view controller**", "**No UIKit whatsoever**",
                "**Only possible** because the search and sort logic lives in the view model"]),
    dict(layout="statement", title="Testability is a consequence of architecture, not an extra step",
         sub="Had that logic stayed in the screen, this test could not exist."),
    dict(layout="statement", title="It goes further",
         sub="These are three fakes from the test file."),
    dict(layout="compare", kicker="Real versus fake", title="Same contract, different weight",
         cols=[dict(head="The real thing",
                    items=["Profile repository writes to disk",
                           "Password store uses the Keychain",
                           "API client makes network calls"]),
               dict(head="The fake", ok=True,
                    items=["Keeps profiles in an array",
                           "Keeps passwords in a dictionary",
                           "Returns canned data instantly"])]),
    dict(layout="statement", title="Each satisfies the same protocol as the real thing",
         sub="So tests hand these in instead — and not one line of production code had to change."),
    dict(layout="points", kicker="Think about the alternative", title="Testing login without this",
         items=["**Writing real files** to disk on every run",
                "**Storing real passwords** in the real Keychain",
                "**Making real network calls** — slow, flaky, and dependent on someone else's server"]),
    dict(layout="shot", kicker="And this is a UI test", title="The app driven automatically",
         images=[shot("02_movies_list.png"), shot("04_reviews_ticketplease.png")],
         items=["**Tapping a category**, opening a film",
                "**Checking the reviews screen**, moving through the booking flow",
                "**No hands** — the same path, every time"]),
    dict(layout="statement", title="One technique worth stealing: assert a button is NOT present",
         sub="Reviews can only be written from a booking, so the test proves the guard holds — absence is as testable as presence."),
    dict(layout="points", kicker="Two practical notes for UI tests", title="Make them survive change",
         items=["**Use accessibility identifiers**, not visible text — copy changes, tests shouldn't break",
                "**Reset state between runs**, or yesterday's data fails today's test"]),
    dict(layout="statement", title="Read the test names in order and you have the specification",
         sub="Ownership, cancellation, validation, the reviews guard — the behaviour of the feature, in order."),
    dict(layout="statement", title="Unlike a document, a test name cannot go stale",
         sub="Because when it stops being true, it fails."),
    dict(layout="points", kicker="Recap", title="Testing",
         items=["Unit tests check logic fast; UI tests prove the whole path",
                "A testable view model needs no screen at all",
                "Fakes satisfying the same protocol replace disk, Keychain and network",
                "Accessibility identifiers and clean state keep tests honest",
                "Test names are the specification that can't go stale"]),
    dict(layout="steps", kicker="Practice exercise", title="Prove one thing automatically",
         items=["Write a unit test for a view model with no UIKit imported",
                "Replace its real store with a fake through a protocol",
                "Add one UI test that asserts something is absent, not present"]),
    dict(layout="statement", title="The final chapter decides whether any of this survives handover",
         sub="Module 10 — Documentation Best Practices."),
]
MODULES[9]["beats"] = SLIDES[9]

# ---------------------------------------------------------------- Module 10
SLIDES[10] = [
    dict(layout="statement", title="Six months from now, somebody opens this project",
         sub="It might be a colleague. It might be you, having forgotten every decision you made."),
    dict(layout="points", kicker="By the end of this video you will be able to", title="Objectives",
         items=["Keep a change list with the five fields that matter",
                "Record AI involvement honestly, at the right depth",
                "Write difficulties and solutions somebody can actually use",
                "Ship documentation that cannot drift from the build"]),
    dict(layout="compare", kicker="Start with the gap", title="What code records, and what it doesn't",
         cols=[dict(head="Code records", items=["What the software does", "Precisely and completely"]),
               dict(head="Code cannot record", warn=True,
                    items=["What you tried and abandoned", "What broke",
                           "What you deliberately left out", "Where you used an AI assistant"])]),
    dict(layout="statement", title="That gap is what documentation fills",
         sub="It is the difference between a project that can be handed over cleanly and one that effectively cannot."),
    dict(layout="table", kicker="A format that works", title="Five fields for every change",
         rows=[("Date", "With the day of the week — it anchors the change in history"),
               ("What changed", "Plain language a non-developer could follow"),
               ("AI involvement", "Whether one was used, and how deeply"),
               ("Difficulties", "What actually went wrong"),
               ("Solutions", "How each one was resolved")]),
    dict(layout="points", kicker="Why the date carries the day of the week",
         title="It anchors the change in the project's history",
         items=["**What changed** — plain language, no jargon",
                "**Whether AI was involved** — stated, even when the answer is none",
                "**What difficulties came up** — and how each was solved"]),
    dict(layout="compare", kicker="The last two are the ones people delete",
         title="They are also the most valuable",
         cols=[dict(head="Without difficulties", warn=True,
                    items=["It reads like marketing"]),
               dict(head="With them", ok=True,
                    items=["It reads like engineering"])]),
    dict(layout="shot", kicker="Here's a real one", title="The change list ships inside the app",
         images=[shot("25_changelog.png")],
         items=["**On the Settings screen**, not in a file nobody opens",
                "**A small decision** that signals the project takes its own history seriously"]),
    dict(layout="code", kicker="And in code", title="Structured, typed data — not loose text",
         code="struct ChangelogEntry: Codable {\n    let date: Date\n    let summary: String\n    let aiInvolvement: AIInvolvement\n    let difficulties: [String]\n    let solutions: [String]\n}",
         pptsize=12,
         note="It can be displayed in the interface, and it can never drift out of sync with the build."),
    dict(layout="compare", kicker="AI involvement", title="Most people get it wrong in one of two directions",
         cols=[dict(head="Over-reporting", warn=True,
                    items=["Logging every autocomplete", "Noise nobody reads"]),
               dict(head="Saying nothing", warn=True,
                    items=["Leaving a reviewer to guess", "Which they will"])]),
    dict(layout="statement", title="Neither avoidance nor concealment",
         sub="Use AI assistants, and use them well. Then record where one helped, at what depth, and what you did to verify the result."),
    dict(layout="table", kicker="A four-level scale is enough", title="Depth of involvement",
         rows=[("None", "No assistant involved"),
               ("Reference", "Used like documentation"),
               ("Assisted", "It drafted something you then reworked"),
               ("Generated", "Used largely as-is — say what you checked")]),
    dict(layout="statement", title="Never commit AI-produced code you can't explain",
         sub="If you couldn't debug it at two in the morning without the assistant, you don't understand it yet."),
    dict(layout="compare", kicker="On difficulties", title="Be specific",
         cols=[dict(head="Helps nobody", warn=True,
                    items=["\"Had trouble with layout\""]),
               dict(head="A colleague can use this", ok=True,
                    items=["\"Constraints looked correct on one device and broke on another; fixed by grouping controls into stack views and constraining the stack\""])]),
    dict(layout="statement", title="Record the decisions you deliberately did not take",
         sub="Choosing JSON files over Core Data is a real decision. Without a note, the next person sees an absence and wonders whether you knew."),
    dict(layout="points", kicker="A checklist to hold your project against", title="Every entry",
         items=["**Has a real date**", "**Says what changed** in plain language",
                "**States AI involvement**, even when it's none",
                "**Difficulties are honest**, not sanitised",
                "**Every difficulty has a matching solution**"]),
    dict(layout="points", kicker="And the rest of it", title="What else the checklist covers",
         items=["**Decisions you didn't take** are recorded",
                "**Known limitations** live somewhere findable, not implied by silence",
                "**Secrets are never** in the change list",
                "**The changelog ships with the build**, so it can't drift"]),
    dict(layout="points", kicker="Recap", title="Documentation Best Practices",
         items=["Code records what the software does — not why, or what failed",
                "Five fields: date, what changed, AI involvement, difficulties, solutions",
                "Record AI depth honestly; never ship code you can't explain",
                "Be specific about difficulties, and record decisions not taken",
                "Ship the changelog with the build so it cannot drift"]),
    dict(layout="steps", kicker="Practice exercise", title="Write a real change list",
         items=["One entry per working session, using all five fields",
                "State AI involvement at one of the four levels, and what you verified",
                "Include one decision you deliberately did not take"]),
    dict(layout="statement", title="And that's the course",
         sub="Seven modules taught you to build an iOS application. Testing proved it works. Documentation is what makes that work survivable by somebody else."),
]
MODULES[10]["beats"] = SLIDES[10]
